### ISSUE TITLE
App name & About page

### ISSUE THREAD

**Issue by benhylau** [hyperboria/android#32]
What should we name this app? Also discussing ideas on what content should go in the [About page](http://berlinmeshnet.github.io/cjdns-android/), which is loaded in a `WebView` in the app.

**Comment by benhylau** [comment]
If someone wants to customize the theme (i.e. brown tint) and manage the **gh-pages** branch that'll be great too.

![device-2015-02-11-233444](https://cloud.githubusercontent.com/assets/2261308/6161884/9f1a1a48-b246-11e4-9be0-89db54038f65.png)

**Comment by sssemil** [comment]
Check it out https://github.com/hyperboria/android/pull/41

**Comment by benhylau** [comment]
Thanks! The new one looks so much better ;P
