### ISSUE TITLE
Use JNI

### ISSUE THREAD

**Issue by sssemil** [hyperboria/android#42]
What about using JNI instead of binary executable?

**Comment by benhylau** [comment]
APIs to start and kill cjdroute, and get peerStats type of info?

**Comment by sssemil** [comment]
It can be used to run all C code. But we can used binary executables anyway.

**Comment by benhylau** [comment]
I thought about going through JNI too, but I don't know enough about that vs. binary executables to say what we'd gain from it. I guess a cleaner API with proper typing? I am definitely open to it. Let's keep this ticket here.

**Comment by lgierth** [comment]
Better to stick with the binary executable -- using JNI means running cjdroute within the Java process, so we'd lose many security features (SSP, Seccomp, chroot, dropping privilieges)
